Repository GreysonElkins/roasted-tomahtoes, pull requests merged in 2020-08, with the labels that each got.

#2 Remove .rtf artifacts
  pull-request-template.md
Labels: documentation

#1 Set up ReadMe shell
  README.md
Labels: documentation

#18 Nav and Search Bar
  src/Search/Search.test.js
Labels: component, testing

#19 Feature/app header comp
  src/App/App.js
  src/App/App.test.js
  src/Header/Header.js
  src/Header/Header.test.js
  src/Nav/Nav.js
  src/Nav/Nav.test.js
  src/index.css
Labels: component, testing

#21 Build main page
  src/API/API-test.js
  src/API/API.js
  src/App/App.js
  src/App/App.scss
  src/Main/Main-test.js
  src/Main/Main.js
  src/Main/Main.scss
  src/MovieCard/MovieCard-test.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.scss
Labels: API, component, styling

#23 Feature/styling gallery
  src/App/App.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/Main/Main.scss
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.scss
  src/Nav/Nav.js
  src/Nav/Nav.scss
  src/Search/Search.js
  src/Search/Search.scss
  src/index.css
Labels: styling

#26 Feature/login
  src/API/API-test.js
  src/API/API.js
  src/App/App.js
  src/App/App.scss
  src/App/App.test.js
  src/Error/Error.js
  src/Error/Error.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/Header/Header.test.js
  src/Login/Login.js
  src/Login/Login.scss
  src/Login/Login.test.js
  src/Main/Main-test.js
  src/Main/Main.js
  src/Main/Main.scss
  src/MovieCard/MovieCard-test.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.scss
  src/Nav/Nav.js
  src/Nav/Nav.scss
  src/Nav/Nav.test.js
  src/Search/Search.js
  src/index.css
Labels: API, styling, testing

#27 Show Page Functionality
  src/API/API.js
  src/App/App.js
  src/Error/Error.js
  src/Error/Error.scss
  src/Main/Main.js
  src/MovieCard/MovieCard.js
  src/MoviePage/MoviePage-test.js
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.scss
Labels: API, component

#30 Feature/showPage
  src/App/App.js
  src/Error/Error.js
  src/Header/Header.scss
  src/Login/Login.js
  src/Login/Login.scss
  src/Main/Main.js
  src/Main/Main.scss
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.scss
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.scss
  src/Nav/Nav.js
  src/Nav/Nav.scss
  src/Nav/Nav.test.js
  src/Search/Search.scss
Labels: component, styling

#36 Feature/refactor scss testing
  src/App/App.js
  src/App/App.scss
  src/Error/Error.js
  src/Error/Error.scss
  src/Header/Header.js
  src/Header/Header.scss
  src/Header/Header.test.js
  src/Login/Login.js
  src/Login/Login.scss
  src/Login/Login.test.js
  src/Main/Main.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.scss
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.scss
  src/Nav/Nav.js
  src/Nav/Nav.scss
  src/Nav/Nav.test.js
  src/Search/Search.scss
  src/index.css
  src/styles/_variables.scss
Labels: component, styling, testing

#37 Implement Search bar
  src/App/App.js
  src/Header/Header.js
  src/Main/Main.js
  src/MoviePage/MoviePage.js
  src/Nav/Nav.js
  src/Search/Search.js
Labels: API, component

#48 Feature/star rating bar
  src/App/App.js
  src/Main/Main.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.scss
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.scss
  src/Rating/Rating.js
  src/Rating/Rating.scss
  src/Rating/Star.scss
Labels: component

#49 Feature/trailer
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/tomato.svg
  src/App/App.js
  src/Header/Header.scss
  src/Main/Main.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.scss
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.scss
  src/Overview/Overview.js
  src/Overview/Overview.scss
  src/Rating/Rating.js
  src/Trailer/Trailer.js
  src/Trailer/Trailer.scss
Labels: API, component, styling

#52 User ratings page
  package-lock.json
  package.json
  src/App/App.js
  src/App/App.test.js
  src/Error/Error.test.js
  src/Header/Header.js
  src/Main/Main.js
  src/Main/Main.test.js
  src/MovieCard/MovieCard.js
  src/MovieCard/MovieCard.scss
  src/MovieCard/MovieCard.test.js
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.test.js
  src/Nav/Nav.js
  src/Overview/Overview.test.js
  src/Rating/Rating.js
  src/Rating/Rating.test.js
  src/Rating/Star.scss
  src/Trailer/Trailer.js
  src/Trailer/Trailer.test.js
Labels: API, component, testing

#54 Feature/AppTesting
  src/App/App.test.js
  src/Main/Main.test.js
  src/Rating/Rating.test.js
Labels: testing

#57 Feature/router
  package-lock.json
  package.json
  public/index.html
  src/App/App.js
  src/Header/Header.js
  src/Header/Header.scss
  src/Login/Login.js
  src/Main/Main.js
  src/MovieCard/MovieCard.js
  src/Nav/Nav.js
  src/Nav/Nav.scss
  src/Search/Search.js
  src/index.js
Labels: component

#58 Refactor API and APP for modularity and dev empathy
  src/API/API.js
  src/App/App.js
Labels: API

#61 Clean up for solo
  src/API/API.js
  src/App/App.js
  src/Main/Main.js
  src/MovieCard/MovieCard.js
Labels: API, help wanted

#62 Feature/ll comments component
  src/API/API.js
  src/App/App.js
  src/App/App.test.js
  src/Comments/Comments.js
  src/Comments/Comments.scss
  src/Comments/Comments.test.js
  src/Main/Main.js
  src/MovieCard/MovieCard.js
  src/MoviePage/MoviePage.js
  src/MoviePage/MoviePage.scss
  src/MoviePage/MoviePage.test.js
  src/Overview/Overview.scss
  src/Search/Search.js
  src/Trailer/Trailer.js
  src/Trailer/Trailer.scss
  src/index.css
Labels: API, component, styling, testing
